FROM tomcat:11.0.0-jdk17    
ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH
RUN mkdir -p "$CATALINA_HOME"
WORKDIR /CATALINA_HOME
RUN apt-get update -y
RUN apt-get -y install curl
